- src/app/pages/market/product.twig
> Disable install button when version has no product.json

- README.md
- src/app/pages/news/9.3/20-improvements.md
- src/app/pages/news/9.3/21-bugfixes.md
- let's look on it as work in progress, adjust titles and flags to
improve these changelogs directly on the issues itself and re-generate
shortly before the official release
> XIVY-6925 list bugFixes and improvements in 9.3 for the 23th Nov

- src/app/pages/news/9.3/01-scaling.md
- src/app/pages/news/9.3/02-config-files.md
- src/app/pages/news/9.3/03-dev-workflowUi.md
- src/app/pages/news/9.3/05-start-inscription.md
- src/app/pages/news/9.3/07-performance.md
- src/app/pages/news/9.3/09-portal.md
- src/app/pages/news/9.3/abstract.html
first de-facto release ready version
> XIVY-6952 polish and streamline 9.3 news

- src/app/pages/deprecation/deprecation.twig
- src/web/assets/css/styles.css
> Improve deprecation page

- src/app/domain/ReleaseInfo.php
- src/app/pages/download/archive/archive.twig
- src/web/releases/ivy/8.0.1/unsafe.version
- test/pages/download/ArchiveActionTest.php
> Improve unsave version mark on archive view

- src/app/domain/ReleaseType.php
- src/app/domain/doc/DocProvider.php
- src/app/pages/doc/DocAction.php
- src/app/pages/doc/DocOverviewAction.php
- src/app/pages/doc/doc.twig
- src/app/pages/doc/overview.twig
- src/app/pages/download/DownloadAction.php
- src/app/pages/download/download.twig
- src/web/assets/css/main.css
- src/web/assets/css/styles.css
- Add dropdown link list to doc le buttons (with news, release notes, migi notes)
- Add release notes link to the download overview page
> Improve doc links

- src/app/pages/deprecation/DeprecationAction.php
- src/app/pages/deprecation/deprecation.json
- src/app/pages/deprecation/deprecation.twig
- src/web/assets/css/styles.css
- test/pages/deprecation/DeprecationActionTest.php
I think these 4 libs we want to remove from the project classpath someday and could be highly used...
I don't know what to link here. So I just made a link to the offical pages, but I don't know if our users do understand what we mean?
> Add old libs to deprecation list

- src/app/pages/deprecation/deprecation.json
Correct releases/deprecation/remove version?
Description improvements?
Other suggestions?
> XIVY-7460 Add features to deprecation list

- src/app/domain/ReleaseInfoRepository.php
- src/app/domain/ReleaseType.php
- src/app/pages/download/DownloadAction.php
- test/pages/download/DownloadActionTest.php
- determine release type from version number given
- easy to setup static links in release-announce pipelines -> flarum
> XIVY-7340 static download links: e.g. download/8.0.1

- src/app/pages/support/support.twig
> Improve support page

- src/app/pages/team/members.json
> Update education title of Jacek in Team

- src/app/pages/news/9.4/20-improvements.md
- src/app/pages/news/9.4/21-bugfixes.md
- src/app/pages/news/9.4/abstract.html
There are not yet improvements for Portal. List can be created with:
https://jenkins.ivyteam.io/job/website-developer_issue-list-generator/job/master/
> XIVY-9123 Add improvements and bugs

- src/app/pages/news/10.0/01-all-le-features.md
- src/app/pages/news/10.0/20-improvements.md
- src/app/pages/news/10.0/21-bugfixes.md
> Remove improvements from new 10

- src/app/pages/doc/overview.twig
> Fix doc buttons if no LE

- src/app/RoutingRules.php
- src/app/pages/api/ApiBrowserAction.php
- src/app/pages/api/api.twig
- test/pages/api/ApiBrowserActionTest.php
Reverts axonivy/website-developer#159
> Revert "Move API Browser to market.axonivy.com"

- src/app/domain/ReleaseType.php
- src/app/pages/download/DownloadAction.php
- test/pages/download/DownloadActionTest.php
> XIVY-10223 Add banners to download pages

- composer.json
- composer.lock
- docker/apache/install-composer.sh
- phpunit.xml.dist
- Upgrade composer to 2.5.5
- Try with * so that dependabot can update deps
> Update composer and no longer stick to specific version in composer.json to let Dependabot update the deps

- src/app/pages/team/members.json
Added Fabian Heuberger as new member in src/app/pages/team/members.json 
Passing all tests
> Added Fabian Heuberger as new member

- src/app/pages/news/11.2/01-notification.md
- src/app/pages/news/11.2/02-portal.md
- src/app/pages/news/11.2/03-inscription-view.md
- src/app/pages/news/11.2/04-engine-cockpit.md
- src/app/pages/news/11.2/05-s3.md
- src/app/pages/news/11.2/06-cron.md
- src/app/pages/news/11.2/07-json.md
- src/app/pages/news/11.2/08-market.md
- src/app/pages/news/11.2/20-improvements.md
- src/app/pages/news/11.2/21-bugfixes.md
- src/app/pages/news/11.2/abstract.html
- src/app/pages/news/11.2/meta.json
Initial version with placeholders for each new feature
> Feature/XIVY-12741 11.22 news page

- src/app/pages/release/release-cycle.twig
Please make an announcement in community.axonivy.com @andreasbalsiger
> Make an extra mile

- src/app/pages/news/11.2/08-market.md
I merge it already, so you can "see" it rendered on the official site: https://dev.axonivy.com/news/11.2
Of course I'm still open for feedback
Furthermore I'll add some images later on.
> let's not be shy about our market efforts

- src/app/pages/news/news-detail-page.twig
Was broken trough jquery removal
> Fix news page gallery

- src/app/pages/news/11.2/03-inscription-view.md
- src/app/pages/news/11.2/04-engine-cockpit.md
- src/app/pages/news/11.2/05-s3.md
- src/app/pages/news/11.2/06-cron.md
- src/app/pages/news/11.2/07-configEditor.md
- src/app/pages/news/11.2/08-market.md
- src/app/pages/news/11.2/abstract.html
Ich hoffe ich hab alle deine Änderungen mitbekommen.
> XIVY-12741 Final tweeks by our PM

- src/app/domain/ReleaseInfoRepository.php
- test/domain/ReleaseInfoTest.php
This will cache the release infos per request.
> Cache release infos

- src/app/pages/deprecation/deprecation.json
@ivy-cst Is there maybe a link to a classic mode doc or also bpmn mode?
> Add classic mode to deprecation feature list

- src/app/pages/news/11.3/01-variable-editor.md
- src/app/pages/news/11.3/02-inscription-view.md
- src/app/pages/news/11.3/03-engine-cockpit.md
- src/app/pages/news/11.3/04-notificationApi.md
- src/app/pages/news/11.3/05-portal.md
- src/app/pages/news/11.3/06-mobileApp.md
- src/app/pages/news/11.3/07-formEditorAlpha.md
- src/app/pages/news/11.3/08-vsCodeDesignerAlpha.md
- src/app/pages/news/11.3/20-improvements.md
- src/app/pages/news/11.3/21-bugfixes.md
- src/app/pages/news/11.3/abstract.html
- src/app/pages/news/11.3/meta.json
bootstrap 11.3 news: defining topics
> prepare release 11.3 docs

- src/app/pages/news/11.3/06-mobileApp.md
App review for iOS was successfull, let's publish the link on the news page!
> Added link i now release iOS Version

- compose.yaml
- composer.json
- composer.lock
- src/app/RoutingRules.php
- src/app/domain/Version.php
- src/app/permalink/MavenPermalinkAction.php
I'll add some tests this afternoon.
> Implement maven artifactory redirect

- src/app/permalink/MavenPermalinkAction.php
- **Implement maven artifactory redirect**
- **Send redirect**
> Send redirect

- src/app/pages/installation/InstallationAction.php
- src/app/pages/installation/_mac_designer.twig
- src/app/pages/installation/installation.twig
- macOS-BETA didn't show mac install instructions
- show terminal step for nightly and dev mac version (as those are not notarized)
> Fix mac installation instructions

- tools/issue-list-generator/pom.xml
- portal now maintains its own release changelog file on github
> XIVY-15201 do not list XIVYPORTAL issues

- composer.lock
Reverts axonivy/dev.axonivy.com#421
> Revert "Update dependency phpunit/phpunit to v11.5.4"

- .gitignore
- Jenkinsfile
- composer.json
- composer.lock
- copy-swagger.php
- src/app/pages/api/ApiBrowserAction.php
- src/app/pages/api/api.twig
- src/web/docs/9.1/openapi/config.json
- src/web/docs/9.1/openapi/default.json
- src/web/docs/9.1/openapi/system.json
- test/pages/api/ApiBrowserActionTest.php
- upgrade very old swagger-ui with known CVE's to latest version .... (already fixes the issue at hand).
- do a short self-check, to only load configs from our own server (referring doc resources)
> XIVY-15883 fix: html-injection vulnerability on dated swagger-ui

- src/app/pages/_parts/base-content.twig
> Add privacy policy and legal notice to footer
